#!/usr/bin/env python3
"""
bc_shim.py - a minimal GNU-bc-compatible stand-in.

The kernel only ever shells out to `bc` from one place, Kbuild:

    (echo $(CONFIG_HZ) | bc -q kernel/time/timeconst.bc) > include/generated/timeconst.h

so this shim implements exactly the semantics of kernel/time/timeconst.bc
(all arithmetic is integer arithmetic, scale=0, obase switches between 10 and 16)
and produces byte-identical output to GNU bc.

Usage:  echo <HZ> | bc_shim.py
        (the `-q` flag and the script filename that the kernel passes are ignored)
"""
import sys


def gcd(a, b):
    while b:
        t = b
        b = a % b
        a = t
    return a


def fmul(b, n, d):
    """(2^b * n + d - 1) / d  -- integer division, bc truncates toward zero."""
    return (2 ** b * n + d - 1) // d


def fadj(b, n, d):
    d = d // gcd(n, d)
    return 2 ** b * (d - 1) // d


def fmuls(b, n, d):
    s = 0
    while True:
        if fmul(s, n, d) >= 2 ** (b - 1):
            return s
        s += 1


def timeconst(hz):
    p = []
    p.append("/* Automatically generated by kernel/time/timeconst.bc */\n")
    p.append("/* Time conversion constants for HZ == %d */\n" % hz)
    p.append("\n")
    p.append("#ifndef KERNEL_TIMECONST_H\n")
    p.append("#define KERNEL_TIMECONST_H\n\n")
    p.append("#include <linux/param.h>\n")
    p.append("#include <linux/types.h>\n\n")
    p.append("#if HZ != %d\n" % hz)
    p.append('#error "include/generated/timeconst.h has the wrong HZ value!"\n')
    p.append("#endif\n\n")

    if hz < 2:
        p.append("#error Totally bogus HZ value!\n")
    else:
        s = fmuls(32, 1000, hz)
        p.append("#define HZ_TO_MSEC_MUL32\tU64_C(0x%x)\n" % fmul(s, 1000, hz))
        p.append("#define HZ_TO_MSEC_ADJ32\tU64_C(0x%x)\n" % fadj(s, 1000, hz))
        p.append("#define HZ_TO_MSEC_SHR32\t%d\n" % s)

        s = fmuls(32, hz, 1000)
        p.append("#define MSEC_TO_HZ_MUL32\tU64_C(0x%x)\n" % fmul(s, hz, 1000))
        p.append("#define MSEC_TO_HZ_ADJ32\tU64_C(0x%x)\n" % fadj(s, hz, 1000))
        p.append("#define MSEC_TO_HZ_SHR32\t%d\n" % s)

        cd = gcd(hz, 1000)
        p.append("#define HZ_TO_MSEC_NUM\t\t%d\n" % (1000 // cd))
        p.append("#define HZ_TO_MSEC_DEN\t\t%d\n" % (hz // cd))
        p.append("#define MSEC_TO_HZ_NUM\t\t%d\n" % (hz // cd))
        p.append("#define MSEC_TO_HZ_DEN\t\t%d\n" % (1000 // cd))
        p.append("\n")

        s = fmuls(32, 1000000, hz)
        p.append("#define HZ_TO_USEC_MUL32\tU64_C(0x%x)\n" % fmul(s, 1000000, hz))
        p.append("#define HZ_TO_USEC_ADJ32\tU64_C(0x%x)\n" % fadj(s, 1000000, hz))
        p.append("#define HZ_TO_USEC_SHR32\t%d\n" % s)

        s = fmuls(32, hz, 1000000)
        p.append("#define USEC_TO_HZ_MUL32\tU64_C(0x%x)\n" % fmul(s, hz, 1000000))
        p.append("#define USEC_TO_HZ_ADJ32\tU64_C(0x%x)\n" % fadj(s, hz, 1000000))
        p.append("#define USEC_TO_HZ_SHR32\t%d\n" % s)

        cd = gcd(hz, 1000000)
        p.append("#define HZ_TO_USEC_NUM\t\t%d\n" % (1000000 // cd))
        p.append("#define HZ_TO_USEC_DEN\t\t%d\n" % (hz // cd))
        p.append("#define USEC_TO_HZ_NUM\t\t%d\n" % (hz // cd))
        p.append("#define USEC_TO_HZ_DEN\t\t%d\n" % (1000000 // cd))

        cd = gcd(hz, 1000000000)
        p.append("#define HZ_TO_NSEC_NUM\t\t%d\n" % (1000000000 // cd))
        p.append("#define HZ_TO_NSEC_DEN\t\t%d\n" % (hz // cd))
        p.append("#define NSEC_TO_HZ_NUM\t\t%d\n" % (hz // cd))
        p.append("#define NSEC_TO_HZ_DEN\t\t%d\n" % (1000000000 // cd))
        p.append("\n")

        p.append("#endif /* KERNEL_TIMECONST_H */\n")

    sys.stdout.write("".join(p))


def main():
    hz = None
    for line in sys.stdin.read().splitlines():
        line = line.strip()
        if line:
            hz = int(line)
            break
    timeconst(100 if hz is None else hz)


main()
